compile: &defaults
  build: .
  volumes:
    - .:/home/kafka/
shell:
  <<: *defaults
  links:
    - zookeeper
    - kafka
  command: bash
zookeeper:
  <<: *defaults
  expose:
    - "2181"
  command: /opt/kafka_2.11-0.9.0.1/bin/zookeeper-server-start.sh /opt/kafka_2.11-0.9.0.1/config/zookeeper.properties
kafka:
  <<: *defaults
  links:
    - zookeeper
  ports:
    - "9092:9092"
  command: /home/kafka/bin/kafka-env-start.sh
